name: lewontin-azure-iot-edge
base: core20
version: '1.2+lewontin' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    architectures: [ amd64, arm64, armhf ]
    components: [ main ]
    suites: [ focal ]
    formats: [ deb ]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/ubuntu/20.04/prod

parts:
  iotedge:
    plugin: nil
    source: .
    stage-packages:
      - aziot-edge
    prime:
      - -lib/
  
  config:
    plugin: dump
    source: ./config

  scripts:
    plugin: dump
    source: ./scripts

apps:
  aziot-edged:
    command-chain: [ create_run_aziot.sh ]
    command: usr/libexec/aziot/aziot-edged
    daemon: simple
    plugs:
      - network-bind
      - sockets
      - docker
      - hostname-control
      - system-observe
  aziot-identityd:
    command-chain: [ create_run_aziot.sh ]
    command: usr/libexec/aziot-identity-service/aziot-identityd
    daemon: simple
    plugs:
      - network-bind
      - sockets
      - mount-observe
  aziot-certd:
    command-chain: [ create_run_aziot.sh ]
    command: usr/libexec/aziot-identity-service/aziot-certd
    daemon: simple
    plugs:
      - network-bind
      - sockets
      - mount-observe
  aziot-keyd:
    command-chain: [ create_run_aziot.sh ]
    command: usr/libexec/aziot-identity-service/aziot-keyd
    daemon: simple
    plugs:
      - network-bind
      - sockets
      - mount-observe
  aziot-tpmd:
    command-chain: [ create_run_aziot.sh ]
    command: usr/libexec/aziot-identity-service/aziot-tpmd
    daemon: simple
    plugs:
      - network-bind
      - sockets
      - mount-observe
      - tpm

  iotedge:
    command: usr/bin/iotedge
    environment:
      IOTEDGE_HOST: "unix:///run/iotedge-mgmt.sock"
    plugs:
      - network
      - docker
      - docker-executables
      - system-observe
      - sockets
  
  aziotctl:
    command: usr/bin/aziotctl
    plugs:
      - network
      - sockets
      - mount-observe

# hooks:
#   install:
#     plugs:
#       - hostname-control

plugs:
  docker-executables:
    interface: content
    content: docker-executables
    target: $SNAP/docker
  sockets:
    interface: system-files
    write:
      - /run/aziot


layout:
  /var/lib/aziot:
    symlink: $SNAP_COMMON/var/lib/aziot
  /etc/aziot:
    symlink: $SNAP_DATA/etc/aziot
  /usr/bin/docker:
    symlink: $SNAP/docker/bin/docker
  # /etc/logrotate.d/aziot-edge:
  #   symlink: $SNAP/etc/logrotate.d/aziot-edge
